const kysymykset = [// kysymys, a, b, c, d, e oikea vastaaus, aihealue(et). Olis pitänyt merkitä oikea vastaus luvulla    
    ["Mikä on oravan tieteellinen nimi?", "Mustela erminea", "Sciurus vulgaris", "Gulo gulo", "Lynx lynx", "Vulpes vulpes", "b", ["luonto"]],
    ["Kuka toimi pisimpään Yhdysvaltain presidenttinä?", "Thomas Jefferson", "Franklin D. Roosevelt", "Abraham Lincoln", "Theodore Roosevelt", "George Washington", "b", ["yleistieto", "historia"]],
    ["Missä maassa shakki keksittiin?","Kiinassa", "Mesopotamiassa", "Persiassa", "Egyptissä", "Intiassa", "e", ["yleistieto", "historia"]],
    ["Kuinka monta tähteä on Euroopan unionin lipussa?", "10", "12", "15", "20", "16", "b", ["yleistieto"]],
    ["Minä vuonna Itä-Rooma (Bysannti) kaatui?", "1492", "1378", "1453", "1346", "476", "c", ["historia"]],
    ["Milloin Musta surma alkoi Euroopassa?", "1312", "542", "1289", "1227", "1346", "e", ["historia"]],
    ["Mikä on maailman syödyin hedelmä?", "Appelsiini", "Omena", "Banaani", "Tomaatti", "Vesimeloni", "d", ["yleistieto"]],
    ["Kuinka monta tähteä on Otavan tähtikuviossa?", "5", "6", "7", "8", "9", "c", ["yleistieto"]],
    ["Missä maassa paperi keksittiin?", "Egyptissä", "Intiassa", "Roomassa", "Mesopotamiassa", "Kiinassa", "e", ["yleistieto", "historia"]],
    ["Mistä maasta pippuri on alunperin kotoisin?",  "Etiopiasta", "Indonesiasta", "Intiasta", "Italiasta", "Meksikosta", "c", ["yleistieto", "maantieto, luonto"]],
    ["Missä maassa juotiin ensimäisenä kahvia?", "Indonesiassa", "Kiinassa", "Turkissa", "Etiopiassa", "Intiassa", "d", ["yleistieto", "historia"]],
    ["Milloin Apollo 11 laskeutui kuuhun?", "1961", "1975", "1984", "1950", "1969", "e", ["yleistieto", "historia", "tiede"]],
    ["Milloin Ranskan suuri vallankumous alkoi?", "1776", "1799", "1789", "1804", "1848", "c", ["yleistieto", "historia"]],
    ["Minä vuosina käytiin Vietnamin sota?", "1955-1975", "1950-1953", "1967-1970", "1979-1989", "1939-1945", "a", ["yleistieto", "historia"]],
    ["Missä kiviaikainen löytöpaikka Göbekli Tepe sijaitsee?", "Iranissa", "Jordanissa", "Turkissa", "Syyriassa", "Pakistanissa", "c", ["yleistieto", "historia", "maantieto"]],
    ["Milloin Napoleon Bonaparte kruunasi itsensä Ranskan keisariksi?", "1799", "1800", "1815", "1821", "1804", "e", ["historia"]],
    ["Mikä oli Mesopotamian ensimmäinen tunnettu sivilisaatio?", "Assyyrialaiset", "Babylonialaiset", "Kaldealaiset", "Sumerit", "Akkadilaiset", "d", ["yleistieto", "historia"]],
    ["Kuka on Suomen menestyinen urheilija Olympialaisissa?", "Paavo Nurmi", "Jari Litmanen", "Lasse Viren", "Matti Nykänen", "Teemu Selänne", "a", ["yleistieto", "suomi"]],
    ["Kuka heistä ei ole suomalainen nobel-palkinnon voittaja?", "Alvar Aalto", "Artturi Ilmari Virtanen", "Bengt Holmström", "Martti Ahtisaari", "Frans Eemil Sillanpää", "a", ["yleistieto", "suomi"]],
    ['Kuka on kirjoittanut kirjan "Sinuhe egyptiläinen?"', "Mika Waltari", "F.E. Sillanpää", "Väinö Linna", "Ilkka Remes", "Tove Jansson", "c", ["yleistieto", "kulttuuri", "suomi"]],
    ["Minä vuonna Wrightin veljekset lensivät ensimmäisen lentonsa lentokoneella?", "1908", "1937", "1899", "1913", "1903", "e", ["yleistieto", "historia", "tiede"]],
    ["Minä vuonna Neuvostoliitto hajosi?", "1989", "1991", "1994", "1984", "1982", "b", ["yleistieto", "historia"]],
    ["Kuka heistä ei ollut kreikkalainen filosofi?", "Sokrates", "Platon", "Aristoteles", "Hippokrates", "Pythagoras", "d", ["yleistieto", "historia"]],
    ["Kuka heistä ei ole kreikkalainen jumala?", "Zeus", "Mars", "Hades", "Poseidon", "Ares", "b", ["yleistieto", "kulttuuri", "historia"]],
    ["Millä nimellä tunnetaan kolmikymmenvuotisessa sodassa toimineet suomalaiset ratsusotilaat?", "Husaarit", "Hakkapeliitat", "Ritarit", "Jääkärit", "Huovit", "b", ["yleistieto", "historia", "suomi"]],
    ["Kuka heistä ei ole brittiläinen kirjailija?", "George Orwell", "Jane Austen", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis", "c", ["yleistieto", "kulttuuri"]],
    ["Mikä on ilveksen tieteellinen nimi?", "Vulpes vulpes", "Sciurus vulgaris", "Gulo gulo", "Lynx lynx", "Felis catus",  "d", ["yleistieto", "luonto"]],
    ["Missä taistelussa Scipio Africanus voitti Hannibalin?", "Zaman taistelussa", "Trebian tastelussa", "Actiumin taistelussa", "Gaugamelan taistelussa", "Cannaen Taistelussa", "a", ["historia"]],
    ["Milloin Yhdysvallat itsenäistyi?", "1801", "1791", "1776", "1812", "1783", "c", ["yleistieto", "historia"]],
    ["Kuka heistä ei ole renessanssiajan taitelija?", "Vincent van Gogh", "Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello", "a", ["yleistieto", "historia", "kulttuuri"]],
    ["Kuka oli Suomen presidentti enimmän ajan jatkosodasta?", "Urho Kekkonen", "Carl Gustaf Emil Mannerheim", "Risto Ryti", "Juho Kusti Paasikivi", "Kyösti Kallio", "c", ["yleistieto", "historia", "suomi"]],
    ["Kuka heistä ei ollut Neuvostoliiton johtaja?", "Nikita Hruštšov", "Leonid Brežnev", "Boris Jeltsin", "Vladimir Lenin", "Mikhail Gorbatsov", "c", ["yleistieto", "historia"]],
    ["Mikä on Kanadan pääkaupunki?", "Vancouver", "Ottawa", "Montreal", "Edmonton", "Toronto", "b", ["yleistieto", "maantieto"]],
    ["Mistä näistä maista on ollut 1800-luvulla siirtomaa?", "Liberia", "Thaimaa", "Bhutan", "Kiina", "Etiopia", "a", ["historia"]],
    ["Mitä väriä ei ole Etiopian lipussa?", "Sinistä", "Keltaista", "Vihreää", "Valkoista", "Punaista", "d", ["yleistieto", "maantieto"]],
    ["Mikä on Suomen kansallispuu?", "Kuusi", "Mänty", "Rauduskoivu", "Hieskoivu", "Kataja", "c", ["luonto", "suomi"]],
    ["Mikä on suurin Jupiterin kuu?", "Ganymedes", "Europa", "Titan", "Io", "Callisto", "a", ["yleistieto", "tiede"]],
    ["Missä taistelussa kreikkalainen laivasto voitti ratkaisevasti persialaisen laivaston?", "Plataiain taistelussa", "Gaugamelan taistelussa", "Salamiin taistelussa", "Marathonin taistelussa", "Issoksen taistelussa", "c", ["historia"]],
    ["Minä vuonna Euroopan Unioini perustettiin?", "1991", "1992", "1993", "1994", "1995", "c", ["yleistieto", "historia"]],
    ["Minkä niminen avaruusluotain ohitti Pluton vuonna 2015?", "Juno", "Voyager 1", "Pioneer 10", "New Horizons", "Voyager 2", "d", ["tiede", "historia"]],
    ["Mikä on Gizan suurimman pyramidin nimi?", "Sfinksin pyramidi", "Kheopsin pyramidi", "Khafren pyramidi", "Cthulhun pyramidi", "Mykerinoksen pyramidi", "b", ["yleistieto", "maantieto", "historia"]],
    ["Mikä on kauimmaksi matkustanut ihmisten luoma asia (2025)?", "Voyager 1", "New Horizons", "Pioneer 10", "Voyager 2", "Pioneer 11", "a", ["yleistieto", "tiede"]],
    ['Keneltä filosofilta on peräisin lausahdus "Ajattelen, siis olen!"?', "Ludwig Wittgensteinilta", "Friedrich Nietzscheltä", "Aristoteleeltä", "Immanuel Kantilta", "René Descartesilta", "e", ["yleistieto"]],
    ["Kuka heistä ei ollut yksi alkuperäisestä kahdestatoista apostolista?", "Pietari", "Juudas", "Tuomas", "Paavali", "Matteus", "d", ["yleistieto"]],
    ["Kuka kruunattiin roomalaisten keisariksi vuonna 800?", "Kaarle Suuri", "Klodvig I", "Filip II Augustus", "Konrad II", "Otto Suuri", "a", ["yleistieto", "historia"]],
    ["Keiksi kutsutaan Uuden Seelannin alkuperäisväestöä?", "Sentineleiksi", "Asteekeiksi", "Aboriginaaleiksi", "Maoreiksi", "Zuluiksi", "d", ["yleistieto", "historia"]],
    ["Kuka heistä ei koskaan hävinnyt taistelua?", "Hannibal", "Aleksanteri Suuri", "Napoleon Bonaparte", "Fredrik Suuri", "Julius Ceasar", "b", ["yleistoeto", "historia"]],
    ["Kuka heistä on hävinnut taistelun?", "Wellington", "Scipio Africanus", "Suvorov", "Khalid ibn al-Walid", "Genghis Khan", "a", ["historia"]],
    ["Mistä maasta alkoi teollinen vallankumous?", "Ranskasta", "Itävallasta", "Saksasta", "Iso-Britanniasta", "Yhdysvalloista", "d", ["yleistieto", "historia"]],
    ["Minä vuonna Yhdysvaltojen sisällissota alkoi?", "1776", "1865", "1789", "1815", "1861", "e", ["historia"]],
    ["Mikä on kullan kemiallinen merkki?", "Fe", "Ag", "Hg", "Cu", "Au", "e", ["yleistieto", "tiede"]],
    ["Mikä on raudan kemiallinen merkkki?", "Mg", "Cr", "Ag", "Al", "Fe", "e", ["yleistieto", "tiede"]],
    ["Mitä uutta asiaa preussilaiset hyödynsivät voitokkaasti Preussin–Itävallan sodassa?", "Tykkiä", "Lentokoneita", "Viistorintamahyökkäystä", "Konekivääreitä", "Junia", "e", ["historia"]],
    ["Mikä seuraavista linnuista muuttaa etelään talveksi?", "Peippo", "Varpunen", "Palokärki", "Harakka", "Talitiainen", "a", ["luonto"]],
    ["Kenen teoksia ovat mm. Monkeys Spinning Monkeys, Local Forecast ja Sneaky Snitch?", "Marshall Mathersin", "Kevin MacLeodin", "Michael Stevensin", "Linus Torvaldsin", "Felix Kjellbergin", "b", ["yleistieto", "kulttuuri"]],
    ["Minkä niminen terroristijärjestö oli vuoden 2001 syyskuun 11. päivän terroritekojen takana?", "Hizbollah", "ISIS", "Hamas", "Taliban", "Al-Qaeda", "e", ["yleistieto", "historia"]],
    ["Mikä näistä on suurin pinta-alaltaan?", "Eurooppa", "Sahara", "Antarktis", "Australia", "Siperia", "c", ["maantieto"]],
    ["Minkä maan pääkaupunki on Damaskos?", "Irakin", "Syyrian", "Egyptin", "Saudi-Arabian", "Iranin", "b", ["maantieto"]],
    ["Mikä on maailman ainoa kahdelle maanosalle jakautuva pääkaupunki?", "Panama", "Suez", "Istanbul", "Singapore", "Jakarta",/*Gibraltar,*/ "c", ["yleistieto", "maantieto"]],
    ["Mille niemimaalle iski dinosaurukset tappava asteroidi?", "Malakan niemimaalle", "Jukatanin niemimaalle", "Skandinavian niemimaalle", "Kuolan niemimaalle", "Iberian niemimaalle", "b", ["maantieto"]],
    ['Kuka on kirjoittanut kirjan "Vuonna 1984"?', "George Orwell", "Suzanne Collins", "Agatha Christie", "Koushun Takami", "Ian Fleming", "a", ["yleistieto", "kulttuuri"]],
    ["Mikä ristirekti onnistuneesti valtasi Jerusalemin?", "Toinen ristiretki", "Viides ristiretki", "Neljäs ristiretki", "Ensimmäinen ristiretki", "Kolmas ristiretki", "d", ["historia"]],
    ["Kuka heistä ei ollut kreikkalainen?", "Ptolemaios I", "Seleukos I Nikator", "Arkhimedes", "Spartacus", "Zenon Kitionilainen", "d", ["historia"]],
    ["Mikä näistä ei sijaitse Kiinassa", "Kielletty kaupunki", "Kiinan muuri", "Tiananmenin aukio", "Terrakotta-armeija", "Himejin linna", "e", ["yleistieto", "maantieto"]],
    ["Missä maassa sijaitsee Angkor Wat?", "Kambodžassa", "Thaimaassa", "Indonesiassa", "Intiassa", "Vietnamissa", "a", ["maantieto"]],
    ["Missä maassa ruuti keksittiin?", "Kiinassa", "Intiassa", "Ranskassa", "Turkissa", "Espanjassa", "a", ["yleistieto", "historia"]],
    ["Mikä operaatio aloitti Saksan hyökkäyksen Neuvostoliittoon?", "Operaatio Sininen", "Operaatio Bagration", "Operaatio Barbarossa", "Operatatio Overlord", "Operaatio Mars", "c", ["yleistieto","historia"]],
    ["Kuka heistä ei ollut tärkeä uskonnollinen henkilö?", "Muhammed", "Martti Luther", "Kungfutse", "Siddhartha Gautama", "Jeesus Nasaterilainen", "c", ["yleistieto"]],
    ["Mistä maasta Godzilla on peräisin?", "Japanista", "Etelä-Koreasta", "Yhdysvalloista", "Taiwanista", "Kiinasta", "a", ["yleistieto", "kulttuuri"]],
    ["Mikä seuraavista ei ole espanjan kielen sana?", "Uno", "Diablo", "Ciao", "Gracias", "Adiós", "c", ["yleistieto", "kulttuuri"]],
    ["Mikä salmi erottaa Välimeren Atlantin valtamerestä?", "Magalhãesinsalmi", "Bosporinsalmi", "Malakansalmi", "Hormuzinsalmi", "Gibraltarinsalmi", "e", ["maantieto"]],
    ["Mikä seuraavista ei ollut yksi talvisodan taisteluista?", "Talin–Ihantalan taistelu", "Raatteen tien taistelu", "Tolvajärven taistelu", "Kollaan taistelu", "Taipaleen taistelu", ["historia"]],
    ["Mikä seuraavista ei sijaitse Italian valtiossa?", /*"Colosseum",*/ "Monte Cassino", "Firenze", "Pisan kalteva torni", "Pompeji", "Vatikaani", "e", ["yleistieto", "maantieto"]],
    ["Mikä seuraavista ei ole suomalainen keksintö?", "Matkapuhelin", "Astiankuivauskaappi", "Molotovin cocktail", "Sykemittari", "Linux", "a", ["yleistieto", "historia", "suomi"]],
    ["Missä Machu Picchu sijaitsee?", "Chilessä", "Meksikossa", "Brasiliassa", "Kolumbiassa", "Perussa", "e", ["maantieto"]],
    ["Mikä on Thaimaan pääkaupunki?", "Naypyidaw", "Jakarta", "Bangkok", "Manila", "Hanoi", "c", ["maantieto"]],
    ["Minkä maan rannikolla sijaitsee Suuri valliriutta?", "Indonesian", "Uuden Seelannin", "Australian", "Papua-Uusi-Guinean", "Yhdysvaltojen", "c", ["maantieto"]],
    ["Milloin on Lucian päivä?", "14. heinäkuuta", "5. helmikuuta", "22. huhtikuuta", "13. joulukuuta", "31. lokakuuta", "d", ["yleistieto", "kulttuuri"]],
    ["Kuka oli Venäjän viimeinen keisari?", "Nikolai II", "Pietari III", "Fredrik II", "Aleksanteri III", "Paavali I", "a", ["yleistieto", "historia"]],
    ["Minkä keisarin alla Rooman imperiumi oli laajimmillaan?", "Hadrianuksen", "Diocletianuksen", "Trajanuksen", "Augustuksen", "Aurelianuksen", "c", ["historia"]],
    ["Ketä pidetään ensimmäisenä historiotsijana?", "Plutarkhosta", "Tacitusta", "Herodotosta", "Liviusta", "Sokratesta", "c", ["yleistieto", "historia"]],
    ["Mikä näistä ei ole yksi antiikin Kreikan kaupunkivaltioista?", "Kórinthos", "Árgos", "Theba", "Sidon", "Sparta", "d", ["historia"]],
    ["Minä vuonna Titanic upposi?", "1912", "1913", "1914", "1915", "1916", "a", ["yleistieto", "historia"]],
    ["Mikä oli pinta-alaltaan maailman suurin valtakunta?", "Venäjän valtakunta", "Mongoolien valtakunta", "Rooman valtakunta", "Espanjalaisten valtakunta", "Brittien valtakunta", "e", ["historia"]],
    ["Mikä on Suomen kansalliskivilaji?", "Dioriitti", "Gneissi", "Kvartsiitti", "Graniitti", "Migmatiitti", "d", ["maantieto", "suomi"]],
    ["Kuka heistä ei ole Harry Potter -kirjasarjassa esiintyvä hahmo?", "Remus Lupin", "Sandor Clegane", "Alastor Vauhkomieli", "Bellatrix Lestrange", "Viktor Krum", ["yleistieto", "kulttuuri"]],
    ["Mikä seuraavista ei ole jäätiköiden aiheuttama maaperän muodostuma?", "Harju", "Suppa", "Raukki", "U-laakso", "Hiidenkirnu", "c", ["maantieto"]],
    ["Minkä pääkaupungin läpi Tonava ei kulje?", "Bukarestin", "Bratislavan", "Belgradin", "Wienin", "Budapestin", "a", ["maantieto"]],
    ["Ketkä eurooppalaiset löysivät ensimmäisenä Australian?", "Portugalilaiset", "Brittiläiset", "Ranskalaiset", "Alankomaalaiset", "Espanjalaiset", "d", ["historia"]],
    ["Mikä on Euroopan korkein vuori?", "Dufourspitze", "Dyhtau", "Elbrus", "Galdhøpiggen", "Mont Blanc", "c", ["yleistieto", "maantieto"]],
    ["Kuka heistä ei ollut yksi valistuksen ajan ajattelioista?", "John Locke", "Rousseau", "Hegel", "Montesquieu", "Adam Smith", "c", ["historia"]],
    ["Minkä nimisestä pyhimyksestä joulupukin hahmo syntyi?", "Pyhä Valentinus", "Pyhä Nikolaos", "Arkkienkeli Mikael", "Pyhä Patrick", "Johannes apostoli", "b", ["yleistieto"]]
]
const helpotKysymykset = [// kysymys, a, b, c, d, oikea vastaaus, aihealue(et)     
    ["Milloin Suomi itsenäistyi?", "1914", "1917", "1939", "1920", "b", ["yleistieto","historia", "suomi"]],
    ["Kuinka monta maanosaa maailmassa on?", "4", "5", "6", "7", "d", ["yleistieto", "maantieto"]],
    ["Mikä on Suomen pääkaupunki?", "Turku", "Tampere", "Oulu", "Helsinki", "d", ["yleistieto", "maantieto", "suomi"]],
    ["Mikä on karhun tieteellinen nimi?", "Canis lupus", "Vulpes vulpes", "Felis catus", "Ursus arctos", "d", ["yleistieto", "luonto"]],
    ["Mikä on pinta-alaltaan maailman suurin valtio?", "Kanada", "Kiina", "Yhdysvallat", "Venäjä", "d", ["yleistieto", "maantieto"]],
    ["Mikä on veden kemiallinen kaava?", "H2O", "CO2", "O2", "NaCl", "a", ["yleistieto", "tiede"]],
    ["Mikä on maailman isoin eläin?", "Kirahvi", "Sinivalas", "Afrikan norsu", "Virtahepo", "b", ["yleistieto", "luonto"]],
    ["Mikä on maapallon korkein vuori?", "K2", "Mont Blanc", "Mount Everest", "Aconcagua", "c", ["yleistieto", "maantieto"]],
    ["Minä vuonna toinen maailmansota loppui?", "1918", "1939", "1945", "1969", "c", ["yleistieto", "historia"]],
    ["Mikä on maailman suurin meri?", "Atlantin valtameri", "Pohjoinen jäämeri", "Tyynimeri", "Intian valtameri", "c", ["yleistieto", "maantieto"]],
    ["Missä maassa sijaitsevat kuuluisat Gizan pyramidit?", "Meksikossa", "Egyptissä", "Kiinassa", "Kreikassa", "b", ["yleistieto", "maantieto"]],
    ["Mikä on Suomen kansalliseläin?", "Karhu", "Susi", "Laulujoutsen", "Ilves", "a", ["yleistieto", "luonto", "suomi"]],
    ["Kuka toimi pisimpään Suomen presidenttinä?", "Urho Kekkonen", "Sauli Niinistö", "Mauno Koivisto", "Carl Gustaf Emil Mannerheim", "a", ["yleistieto", "historia", "suomi"]],
    ["Minä vuonna Waterloon taistelu käytiin?", "1812", "1815", "1809", "1805", "b", ["historia"]],
    ["Millä tunturilla sijaitsee Suomen korkein kohta?", "Haltilla", "Yllästunturilla", "Saanalla", "Saariselällä", "a", ["yleistieto", "maantieto", "suomi"]],
    ["Mikä on maailman suurin järvi?", "Victorianjärvi", "Kaspianmeri", "Laatokka", "Yläjärvi", "b", ["yleistieto", "maantieto"]],
    ["Mikä on Venäjän pääkaupunki?", "Novosibirsk", "Moskova", "Nižni Novgorod", "Pietari", "b", ["yleistieto", "maantieto"]],
    ["Mikä on ruokasuolan kemiaalinen kaava?", "HCl", "CaCl2", "MgCl2", "NaCl", "d", ["yleistieto", "tiede"]],
    ["Mikä on suden tieteellinen nimi?", "Felis catus", "Ursus arctos", "Canis lupus", "Vulpes vulpes", "c", ["yleistieto", "luonto"]],
    ["Mikä on Euroopan pisin joki?", "Seine", "Tonava", "Rein", "Volga", "d", ["yleistieto", "maantieto"]],
    ["Kuka keksi yleisen suhteellisuusteorian?", "Isaac Newton", "Nikola Tesla", "Max Planck", "Albert Einstein", "d", ["yleistieto", "tiede"]],
    ["Mikä oli Suomen pääkaupunki ennen Helsinkiä?", "Tampere", "Viipuri", "Porvoo", "Turku", "d", ["yleistieto", "historia", "suomi"]],
    ["Minä vuonna ensimmäinen versio Minecraftista julkaistiin?", "2009", "2010", "2011", "2012", "a", ["yleistieto"]],
    ["Minu vuonna iPhone julkaistiin?", "2005", "2006", "2007", "2008", "c", ["yleistieto", "tiede"]],
    ["Minä vuonna alkoi ensimmäinen maailmansota?", "1853", "1939", "1815", "1914", "d", ["yleistieto", "historia"]],
    ["Kuka oli ensimmäinen ihminen avaruudessa?", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Sergei Korolev", "b", ["yleistieto", "historia", "tiede"]],
    ["Mikä on Suomen kansalliskala?", "Lohi", "Siika", "Ahven", "Hauki", "c", ["yleistieto", "luonto", "suomi"]],
    ["Kuka heistä ei ollut mukana perustamassa Applea?", "Steve Wozniak", "Bill Gates", "Steve Jobs", "Ronald Wayne", "b", ["yleistieto", "tiede"]],
    ["Mikä on Saksan pääkaupunki?", "Wien", "Frankfurt", "Berliini", "Hampuri", "c", ["yleistieto", "maantieto"]],
    ["Kuka oli Rooman ensimmäinen keisari?", "Julius Caesar", "Nero", "Augustus", "Caligula", "c", ["yleistieto", "historia"]],
    ["Mikä on nopein maaeläin?", "Hanka-antilooppi", "Leijona", "Hyppygaselli", "Gepardi", "d", ["yleistieto", "luonto"]],
    ["Mikä on maailman suurin saari?", "Grönlanti", "Madagaskar", "Uusi-Guinea", "Australia", "a", ["yleistieto", "maantieto"]],
    ["Mikä on maailman suurin sademetsä?", "Kongon sademetsä", "Australaasian sademetsä", "Amazonin sademetsä", "Borneon sademetsä", "c", ["yleistieto", "maantieto", "luonto"]],
    ["Minä vuonna alkoi Venäjän iso hyökkäys Ukrainaan?", "2020", "2021", "2022", "2023", "c", ["yleistieto", "historia"]],
    ["Mikä eläin on Suomen vaakunassa?", "Ilves", "Leijona", "Karhu", "Susi", "b", ["yleistieto", "suomi"]],
    ["Kuinka monta kirjaa on Harry Potter -sarjassa?", "5", "6", "7", "8", "c", ["yleistieto", "kulttuuri"]],
    ["Mitä tapahtui 11.9.2001?", "Terroristit hyökkäsivät World Trade Centeriin", "Sota Irakissa alkoi", "Yhdysvallat hyökkäsi Afganistaniin", "Jugoslavia hajoaminen alkoi", "a", ["yleistieto", "historia"]],
    ["Mikä on ihmisen suurin elin?", "Maksa", "Aivot", "Iho", "Keuhkot", "c", ["yleistieto", "tiede"]],
    ["Kuinka monta tähteä on Yhdysvaltain lipussa?", "5", "50", "49", "51", "b", ["yleistieto", "maantieto"]],
    ["Mikä on Iso-Britannian pääkaupunki?", "Pariisi", "Manchester", "Liverpool", "Lontoo", "d", ["yleistieto", "maantieto"]],
    ["Mikä on Italian pääkaupunki?", "Venetsia", "Milan", "Rooma", "Napoli", "c", ["yleistieto", "maantieto"]],
    ["Mikä on Aku Ankan auton rekisterinumero?", "313", "123", "777", "911", "a", ["yleistieto", "kulttuuri", "suomi"]],
    ["Kuka astui Kuun pinnalle ensimmäisenä?", "Michael Collins", "Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong",  "d", ["yleistieto", "historia"]],
    ["Kuinka monta jalkaa hämähäkeillä on?", "8", "6", "10", "12", "a", ["yleistieto", "luonto"]],
    ["Minä vuosina tavallisesti sanotaan keskiajan olleen?", "476-1350", "1453-1700", "1776-1914", "476-1453", "d", ["yleistieto", "historia"]],
    ["Mikä on Suomen ainoa luonnonvarainen myrkkykäärme?", "Kyy", "Vaskitsa", "Kangaskäärme", "Rantakäärme", "a", ["yleistieto", "luonto", "suomi"]],
    ["Miksi kutsuttiin muinaisen Egyptin kuninkaita?", "Keisareiksi", "Sulttaaneiksi", "Kaliffeiksi", "Faaraoiksi", "d", ["yleistieto", "historia"]],
    ["Mistä maasta anime on peräisin?", "Ranskasta", "Japanista", "Yhdysvalloista", "Kiinasta", "b", ["yleistieto"]],
    ["Mikä on Youtuben katsotuin video (2025)?", "Gangnam Style", "The Wheels on the Bus", "Despacito", "Baby Shark Dance", "d", ["yleistieto"]],
    ["Mikä on Youtuben tilatuin kanava (2025)?", "T-Series", "Cocomelon", "Vlad and Niki", "MrBeast", "d", ["yleistieto"]],
    ["Kuka loi muumit?", "Tove Jansson", "Mauri Kunnas", "Astrid Lindgren", "Timo Parvela", "a", ["yleistieto", "kulttuuri"]],
    ["Mikä on Ruotsin pääkaupunki?", "Tukholma", "Malmö", "Uppsala", "Göteborg", "a", ["yleistieto", "maantieto"]],
    ["Mikä on Suomen kansalliskukka?", "Kielo", "Voikukka", "Sinikello", "Maitohorsma", "a", ["yleistieto", "luonto", "suomi"]],
    ["Minkä meren äärellä Suomi on?", "Itämeren", "Pohjoisen jäämeren", "Välimeren", "Atlantin valtameren", "a", ["yleistieto", "maantieto", "suomi"]],
    ["Mikä on väkiluvultaan suurin kaupunki (2025)?", "New York", "Shanghai", "Tokio", "Delhi", "c", ["yleistieto", "maantieto"]],
    ["Kuka heistä ei ollut mukana yhdistämässä Saksaa 1860-70 -luvuilla?", "Otto von Bismarck", "Vilhelm I", "Helmuth von Moltke", "Adolf Hitler", "d", ["yleistieto", "historia"]],
    ["Mikä on suosituin suomalainen etunimi?", "Helena", "Juhani", "Maria", "Johannes", "c", ["yleistieto", "suomi"]],
    ["Kuinka monta bittiä on yhdessä tavussa?", "8", "10", "12", "16", "a", ["yleistieto", "tiede"]],
    ["Mikä on hiilen kemiallinen merkki?", "C", "O", "P", "H", "a", ["yleistieto", "tiede"]],
    ["Mikä on hapen kemiallinen merkki?", "O", "F", "H", "C", "a", ["yleistieto", "tiede"]],
    ["Mikä planeetta tunnetaan sen renkaista?", "Uranus", "Saturnus", "Jupiter", "Neptunus", "b", ["yleistieto", "tiede"]],
    ["Kuinka monta ruutua on shakkilaudassa?", "49", "64", "50", "81", "b", ["yleistieto", "kulttuuri"]],
    ["Mitä näistä eläimistä on vähiten Suomessa?", "Lepakkoja", "Saimaannorppia", "Karhuja", "Ilveksiä", "b", ["yleistieto", "luonto"]],
    ["Mikä näistä ei ole Helsingissä?", "Näsinneula", "Senaatintori", "Ateneum", "Linnanmäki", "a", ["yleistieto", "suomi"]],
    ["Mikä on Suomen yleisin sukunimi?", "Korhonen", "Virtanen", "Mäkinen", "Nieminen", "a", ["yleistieto", "suomi"]],
    ["Kuka kirjoitti Taru sormusten herrasta -romaanin?", "C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "b", ["yleistieto", "kulttuuri"]],
    ["Mikä joki kulkee Egyptin läpi?", "Niili", "Mississippi", "Amazon", "Keltainenjoki", "a", ["yleistieto", "maantieto"]],
    ["Mikä on suurin maanosa?", "Afrikka", "Pohjois-Amerikka", "Etelä-Amerikka", "Aasia", "d", ["yleistieto", "maantieto"]],
    ["Kuka on kaikkien aikojen menestynein pikajuoksija?", "Usain Bolt", "Jim Thorpe", "David Goggins", "Michael Jordan", "a", ["yleistieto", "urheilu"]],
    ["Mikä yritys loi Angry Birds -pelisarjan?", "Mojang", "Supercell", "Rovio", "Epic Games", "c", ["yleistieto", "kulttuuri"]],
    ["Kuka kirjoitti Harry Potter -kirjasarjan?", "J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "Astrid Lindgren", ["yleistieto", "kulttuuri"]],
    ["Kuka perusti Amazon-verkkokaupan?", "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos", "d", ["yleistieto"]],
    ["Minkä nimesessä tapahtumassa aine muuttuu suoraan kiinteästä kaasuksi?", "Höyrystyminen", "Tiivistyminen", "Härmistyminen", "Sublimoituminen", "d", ["yleistieto", "tiede"]],
    ["Mikä näistä ei ole yksi Pohjoismaista?", "Viro", "Islanti", "Suomi", "Tanska", "a", ["yleistieto", "maantieto"]],
    ["Mikä yritys kehittää Minecraftia?", "Epic Games", "Mojang", "Re-Logic", "Nintendo", "b", ["yleistieto", "kulttuuri"]],
    ["Minkä nimisessä galaksissa elämme?", "Linnunrata", "Andromedan galaksi", "Messier 1", "Kolmion galaksi", "a", ["yleistieto", "tiede"]],
    ["Mikä näistä uskonnoista ei alkunut Lähi-Idästä?", "Nämä kaikki alkoivat", "Juutalaisuus", "Kristinusko", "Islam", "a", ["yleistieto", "kulttuuri"]],
    ["Milloin aprilliä vietetään?", "1. huhtikuuta", "5. helmikuuta", "13. tammikuuta", "4. heinäkuuta", "a", ["yleistieto", "kulttuuri"]],
    ["Milloin on Suomen itsenäisyyspäivä?", "10. joulukuuta", "31. joulukuuta", "6. joulukuuta", "25. joulukuuta", "c", ["yleistieto", "suomi"]],
    ["Missä sarjassa esiintyy Darth Vader?", "Star Warsissa", "Star Trekissä", "The Lord of the Ringsissä", "Harry Potterissa", "a", ["yleistieto", "kulttuuri"]],
    ["Mikä on Suomen suurin järvi?", "Päijänne", "Peilinen", "Inarijärvi", "Saimaa", "d", ["yleistieto", "maantieto", "suomi"]],
    ["Mikä näistä yleistyi viimeisenä?", "Televisio", "Radio", "Tietokone", "Kamera", "c", ["yleistieto", "kulttuuri", "historia"]],
    ["Mikä seuraavista ei ole suomalaisen keksimä peli?", "Pöytäjääkiekko", "Clash of Clans", "Angry Birds", "Afrikan tähti", "a", ["yleistieto", "kulttuuri", "suomi"]],
    ["Minkä kuukauden viimeisenä päivänä on Halloween?", "Syyskuun", "Lokakuun", "Marraskuun", "Heinäkuun", "b", ["yleistieto", "kulttuuri"]],
    ["Kuka oli Yhdysvaltain presidentti sisällissodan aikana?", "Andrew Jackson", "Franklin D. Roosevelt", "George Washington", "Abraham Lincoln", "d", ["historia"]],
    ["Mikä on veden olomoto?", "neste", "hyöry", "kiinteä", "plasma", "a", ["yleistieto", "tiede"]],
    ["Missä maassa sijaitsee maailman korkein rakennus Burj Khalifa?", "Intiassa", "Yhdistyneissä arabiemiraateissa", "Saudi-Arabiassa", "Kiinassa", "b", ["yleistieto", "maantieto"]],
    ["Mikä oli Jeesuksen äidin nimi?", "Rebekka", "Maria", "Saara", "Eeva", "b", ["yleistieto"]],
    ["Minkä puun lehti on Kanadan lipussa?", "Pihlajan", "Vaahteran", "Lepän", "Tammen", "b", ["yleistieto", "maantieto"]],
    ["Millä nimellä kutsutaan Ruotsin valuuttaa?", "Kruunu", "Punta", "Rupla", "Euro", "a", ["yleistieto"]],
    ["Millä nimellä kutsutaan Iso-Britannian valuuttaa?", "Rupla", "Euro", "Punta", "Kruunu", "c", ["yleistieto"]],
    ["Mikä planeetta tunnetaan sen suuresta punaisesta pilkusta?", "Saturnus", "Neptunus", "Uranus", "Jupiter", "d", ["yleistieto", "tiede"]],
    ["Kuinka paljon suunnilleen painaa litra vettä?", "200 g", "500 g", "1 kg", "2 kg", "c", ["yleistieto", "tiede"]],
    ["Mikä on maailman puhutuin kieli?", "Mandariinikiina", "Hindi", "Espanja", "Englanti", "d", ["yleistieto", "kulttuuri"]], //Mandariinikiinalla on eniten äidinkielenä puhuvia
    ["Mitä vuoristoa pidetään Euroopan itärajana?", "Karpaatit", "Kaukasus", "Altai", "Ural", "d", ["maantieto"]]
]
const vaikeatKysymykset = [// kysymys, a, b, c, d, e, f oikea vastaaus, aihealue(et)   
    ["Minä vuonna Stalin kuoli?", "1953", "1947", "1961", "1950", "1949", "1945", "a", ["historia"]],
    ["Kuka voitti ensimmäisenä kaksi Nobel-palkintoa?", "Niels Bohr", "Linus Pauling", "Albert Einstein", "John Bardeen", "Max Planck", "Marie Curie", "f", ["yleistieto", "historia", "tiede"]],
    ["Minä vuonna Kolumbus saapui Amerikkaan?", "1501", "1485", "1510", "1476", "1498", "1492", "f", ["yleistieto", "historia"]],
    ["Minä päivänä talvisota alkoi?", "1.12.1939", "28.11.1939", "26.11.1939", "5.12.1939", "30.11.1939", "10.12.1939", "e", ["yleistieto", "historia", "suomi"]],
    ["Minkä ikäisennä Aleksanteri Suuri kuoli?", "25", "32", "18", "20", "28", "22", "b", ["historia"]],
    ["Minkä näistä taisteluista Napoleon hävisi?", "Austerlitzin taistelu", "Trafalgarin taistelu", "Marengon taistelu", "Wagramin taistelu", "Friedlandin taistelu", "Leipzigin taistelu", "f", ["historia"]],
    //["Mitä seuraavista Leonardo da Vinci ei tehnyt", "Edistänyt huomattavasti anatomian kehitystä", "Veistänyt David-patsasta", "Maalannut kalleinta huutokaupassa myytyä maalausta", "Maalannut Mona Lisaa", 'Suunnitellut "panssarivaunua"', "Suunitellut laskuvarjoa ja helikopteria", "b", ["historia", "kulttuuri"]],
    ["Mikä seuraavista Leonardo da Vinci ei ollut?", "Arkkitehti", "Psykologi", "Kasvistieteilijä", "Anatomi", "Insinööri", "Muusikko", "Taidemaalari", "b", ["yleistieto", "historia"]],
    ["Mikä on maailman metsäisin maa?", "Gabon", "Suomi", "Päiväntasaajan Guinea", "Bhutan", "Laos", "Suriname", "f", ["yleistieto", "luonto", "maantieto"]],
    ["Mitä näistä on vähiten / ei ollenkaan epäilty syyksi pronssikauden päättymiselle Itä-Välimerellä?", "Sisällissotia", "Meteoriitin iskua", "Tulivuoren purkausta", "Kuivuuden aiheuttamaa nälänhätää", "Maanjäristyksiä", "Merikansojen hyökkäystä", "b", ["historia"]],
    ["Mistä seuraavista maista kaivetaan timantteja vähiten?", "Kanadasta", "Etelä-Afrikasta", "Australiasta", "Venäjältä", "Botswanasta", "Kiinasta", "f", ["maantieto"]],
    ["Millä seuraavista nimistä ei ole raamatullisia juuria?", "Pekka", "Saara", "Joona", "Laura", "Elias", "Juhani", "d", ["yleistieto", "kulttuuri"]],
    //['Minkä tulivuoren purkaus aiheutti "kesättömän vuoden 1816"?', "Krakatau", "Hekla", "Tambora", "St. Helens", "Vesuvius", "Etna", "c", ["historia"]],
    ['Minkä tulivuoren purkausta pidetään rajuimpana historiassa?', "Krakataun", "Heklan", "Tamboran", "St. Helensin", "Vesuviuksen", "Etnan", "c", ["yleistieto"]],
    ["Mikä seuraavista ei saapunut Eurooppaan Amerikasta?", "Peruna", "Tomaatti", "Kaakao", "Appelsiini", "Maissi", "Tupakka", "d", ["historia", "maantieto"]],
    ["Minä vuonna Gutenberg keksi kirjapainon?", "1420", "1430", "1440", "1450", "1460", "1470", "c", ["yleistieto", "historia"]],
    ["Mistä vanhin tunettu asiakasvalitus valitti?", "Tikarin tylsyydestä", "Sandaalien väärästä koosta", "Tinatilauksen myöhästymisestä", "Viinin huonosta laadusta", /*Ea-nāṣirin */"Huonosta kuparin laadusta", "Viljalastin homehtumisesta", "e", ["historia"]],
    ["Mikä seuraavista asioista tai asioista ei alun perin tullut antiikin Kreikasta?", "Pythagoraan lause", "Logiikka", "Teatteri", "Heliosentrismi", "Analoginen tietokone", "Maapallon pyöreys", "a", ["historia"]],
    ["Kuka heistä ei ollut italialainen?", "Antonio Vivaldi", "Leonardo da Vinci", "Pablo Picasso", "Kristoffer Kolumbus", "Enrico Fermi", "Galileo Galilei", "c", ["historia"]], //Ei maailman vaikein kysymys
    ["Millä nimellä kuningas Ozymandias paremmin tunnetaan?", "Kyyros Suuri", "Ramses II", "Hammurabi", "Sargon Suuri", "Dareios I", "Thutmose III", "b", ["historia"]],
    ["Mikä on Mongolian pääkaupunki?", "Ulaanbaatar", "Biškek", "Pjongjang", "Astana", "Samarkand", "Irkutsk", "a", ["maantieto"]],
    ["Mikä seuraavista ei ollut yksi alkuperäisestä seitsemästä ihmeestä?", "Faaroksen majakka", "Rhodoksen kolossi", "Sofian mausoleumi", "Artemiin temppeli",/*"Gizan suuri pyramidi",*/ "Zeuksen kuvapatsas", "Babylonin riippuvat puutarhat", "c", ["historia"]],
    ["Mikä on Kenian pääkaupunki?", "Mogadishu", "Nairobi", "Sansibar", "Mombasa", "Addis Abeba", "Kampala", "b", ["maantieto"]],
    ["Milloin ensimmäiset ns. Kuolleenmeren kääröt löydettiin?", "1934", "1975", "1953", "1968", "1956", "1947", "f", ["historia"]],
    ["Kuka kirjoitti Odysseian?", "Herodotos", "Menandros", "Homeros", "Hesiodos", "Ksenofon", "Aiskhylos", "c", ["historia", "kulttuuri"]],
    ["Mikä oli Carringtonin tapahtuma?", "Asteroidin törmäys Jupiteriin", "Magneettisen napojen vaihtuminen", /*Dinosauruksien tappava tapahtuma*/ "Historian voimakkain maanjäristys", "Historian suurin aurinkomyrsky", "Merenpinnan nopea nousu n. 11 000 vuootta sitten", '"Uuden tähden" ilmestyminen taivaalle väliaikaisesti', /*"Asteroidin räjähdys ilmakehässä"*/ "d", ["historia", "tiede"]],
    ["Mikä on kielellisesti monimuotoisin maa?", "Uganda", "Papua-Uusi-Guinea", "Nigeria", "Indonesia", "Kongon demokraattinen tasavalta", "Intia", "b", ["yleistieto", "kulttuuri"]]
]